/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Curator } from './Curator';
export * as factories from './factories';
export { Curator__factory } from './factories/Curator__factory';
